$(document).ready( 
	function(){ 
		$("#option0").click( 
			function(){ 
				$("#mpci-featured-overlay0").slideDown("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product0").slideUp("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option1").click( 
			function(){ 
				$("#mpci-featured-overlay1").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product1").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option2").click( 
			function(){ 
				$("#mpci-featured-overlay2").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product2").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option3").click( 
			function(){ 
				$("#mpci-featured-overlay3").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product3").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option4").click( 
			function(){ 
				$("#mpci-featured-overlay4").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product4").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option5").click( 
			function(){ 
				$("#mpci-featured-overlay5").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product5").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option6").click( 
			function(){ 
				$("#mpci-featured-overlay6").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product6").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option7").click( 
			function(){ 
				$("#mpci-featured-overlay7").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay8").slideUp("slow");
				$("#mpci-product7").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product8").slideDown("slow");
			}
		);
		$("#option8").click( 
			function(){ 
				$("#mpci-featured-overlay8").slideDown("slow");
				$("#mpci-featured-overlay0").slideUp("slow");
				$("#mpci-featured-overlay1").slideUp("slow");
				$("#mpci-featured-overlay2").slideUp("slow");
				$("#mpci-featured-overlay3").slideUp("slow");
				$("#mpci-featured-overlay4").slideUp("slow");
				$("#mpci-featured-overlay5").slideUp("slow");
				$("#mpci-featured-overlay6").slideUp("slow");
				$("#mpci-featured-overlay7").slideUp("slow");
				$("#mpci-product8").slideUp("slow");
				$(".mpci-product0").slideDown("slow");
				$(".mpci-product1").slideDown("slow");
				$(".mpci-product2").slideDown("slow");
				$(".mpci-product3").slideDown("slow");
				$(".mpci-product4").slideDown("slow");
				$(".mpci-product5").slideDown("slow");
				$(".mpci-product6").slideDown("slow");
				$(".mpci-product7").slideDown("slow");
			}
		);
	}
);
